config/routes.rb
Brandsales::Application.routes.draw do
  resources :orders
  resources :shopifystores
  
  match 'auth/shopify/callback' => 'login#finalize'
  
  match '/charge/confirm'    => 'charge#confirm', :as => :confirm
  match 'charge'             => 'charge#index', :as => :charge
  
  match 'home'      => 'home#index'
  match 'customergroups'      => 'customergroups#index'
  match 'customercountries'  => 'customercountries#index'
  match '/orders/search_orders/'     => 'orders#search_orders'
  match '/home/checkjob/'     => 'home#checkjob'
  
  match 'welcome'            => 'home#welcome'

  match 'design'             => 'home#design'

  match 'login'              => 'login#index',        :as => :login

  match 'login/authenticate' => 'login#authenticate', :as => :authenticate
 
  match 'login/finalize'     => 'login#finalize',     :as => :finalize

  match 'login/logout'       => 'login#logout',       :as => :logout
  
  
  match 'initial_pull'       => 'home#initial_pull', :as => 'initial_pull'
  match 'pull_all_orders'    => 'home#pull_all_orders', :as => 'pull_all_orders'
  match 'delayedjoborderfetch'    => 'home#delayedjoborderfetch', :as => 'delayedjoborderfetch'
  match 'orders'			     => 'orders#index'
  match '/home/select_orders_of_year' => "home#select_orders_of_year"
  root :to                   => 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Brand Sales Report - 78e</title>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>

<body>
	
  <div id="header">
    <h1><%= link_to 'Brand Sales Report', '/' %></h1>
    
    <p id="login-link">
      <% if shop_session %>
          <span class="note">current shop</span> <%= link_to shop_session.url, "https://#{shop_session.url}", :class => 'shop_name' %> <span class="note">|</span>
          <%#= link_to 'List Orders', orders_path %><span class="note">|</span>
          <%= link_to 'logout', logout_path %>
      <% end %>
    </p>
  </div>

  <div id="container" class="clearfix">
    <ul id="tabs">
	<%= tab :index, {:controller => '/home'}, :label => 'Vendor' %>
 	<%= tab :index, {:controller => '/customergroups'}, :label => 'Customer Groups' %>
	<%= tab :index, {:controller => '/customercountries'}, :label => 'Country' %>
      <%= tab :orders, {:controller => '/orders'}, :label => 'Last 100 Orders' %>
    </ul>
    
    <!-- Flash error & notice-->
    <% if flash[:error] %> <div id="flasherrors"><%= flash[:error] %></div><% end %>
    <% if flash[:notice] %><div id="flashnotices"><%= flash[:notice] %></div><% end %>
  
    <!-- begin div.main-->
    <div id="main">
      <%= yield %>
    </div>
    <!-- end div.main -->
  </div>
<script type="text/javascript">
  var uvOptions = {};
  (function() {
    var uv = document.createElement('script'); uv.type = 'text/javascript'; uv.async = true;
    uv.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'widget.uservoice.com/uKFB2B3OZVoRrWrpfK1ow.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(uv, s);
  })();
</script>
</body>
</html>